language: python
services:
- postgresql
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database personal_dashboard_test;' -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ZwDaXZY6TIiUOYcW2Fpndp3BIGmrIE0rkml9tC0lS5+rv33i2gc4oBeuBQnHj43pAJIgYiqq/T7ZnoUP3CtoAVPKFxwB/q2nCpyHi4QAcQmy0Ebwc4OSgzYuoV5a2W8FZpN9MY2kjsVxRHcXCaGjSJmHP695BG20X763qro2N7kFGLx21XYhm+Zjvq/kLQVaVPdJ1cgvKxY7mANZx9sEq7YDo/8CT+t11pY2pVY3b/G+GIo2TTYKGxxJtvMNseQi+3bjMcWpEu6Lv0Dv7IxK0ARyEXPNmMXHIa8hHi+Sg3oksa9XcBgUlY/GIa6ou9OLJT6dyaGY102+ymW/7+6xUI9+GFbDEmMJJ3WHrnrjvyNq58YZBJDhw0+NFtP9fBtgiK/zEuKSPAndPjpRHAm7is3FLEHRfCBmZlyvUqD9nz6i+SMAWoNUPdDXpO5JXAF38Ixxw3vvNMsPLA0DBSnD/5xAZ5dRkYtmnFE1cNduR84EfJ1ojl4t9uKEpvKWouElmDmVzSKspSgmpl0zxfnSaC8ZFE/ghb0lE26sXjP3hJ2KjxvUmhuHprsTkzvhykWcENDca0LxcpBEpMfRkp4QQn5Da77bRg1KCwnFs68fuNnjPPuQpM+k5+aFfx8TNg5r7gEh0iAj5zL91ZViiP8jLkQHYtjDNgmMRzaoIiwkHTo=
  app: project-102-bogo-sorters
  on:
    repo: uva-cs3240-s20/project-102-bogo-sorters
    branch: master
