language: python
services:
- postgresql
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database personal_dashboard_test;' -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: l+EnFxgPw1fKZe/y+i3GeIRziR1nL4aUiOFnMBtHMeIda+Kiaw8zLrU4YkkVTd7Yj4If5/vKXcLYUh1mRKvRiFR+mVSkR4+xtO29lyB4EhH3pkpNaDqdt8Vy2cAqbT0Bu53AuoVER/m1niw5xwdevjlQLzZaTRRsUb5HOlJjX77psuRQEMEmXvbTvfMorDnDwvWXSZ1/apC2PB0fEcqJGITd1UiLf8f3ab1fUDOYTjA+hmkzMVhwjOeKWeJXYV+VaK+1wI7YhtiCkLnn5Q2HEqbW/eXDvOZufeE3WvjXDx8it9SoUxl2WdaFG1oMXXG1LpcmGJJizgV0aaf547YVcJYi95VywkBMvLhhcmI/l1bCu7HSFf8agOl2lr8aeEdk4tlmSIxt3wgDYucVCV64ey2cV45iKw28malC9kTG5k9XgUv9ZFZoEjQoChhN2qvy1iATKonjYandS+xFG5eCFFXdfD8dNg5topzsvtUZO+JMSg88jFV2PqTCjn0WQGPGzqADm8qC1H/DCMdk1j/cvc8NjCq49DFzsID0fP45U33rHVfR8geoWwpfaK/TgVzx5dbSikwHM7Yw8zuUrA5v6eMbkSDqPdJmmp7GwdexFd1+mtMRvKXDMw91mh6yCYf48wA1NLnPTQcZHm1oV8VjYAIXHxobzs5QRfEOH8z6gzE=
  app: project-102-bogo-sorters
  on:
    repo: uva-cs3240-s20/project-102-bogo-sorters
    branch: travis-ci
